version: '3'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      # can be accessed with DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
    ports:
      - 5432:5432
